cms/urls.py
from django.conf.urls import patterns, url
from cms import views
from django.conf import settings

urlpatterns = patterns('',
    url(r'^gatya/drop/$', views.drop_item, name='drop_item'),
    url(r'^gatya/$', views.main_pic, name='main_pic'),
    url(r'^gatya/zukan/$', views.zukan, name='zukan'),
    url(r'^gatya/reset/$', views.drop_reset, name='reset'),
    url(r'^gatya/game/highandlow/$', views.high_and_low, name='high_and_low'),
    url(r'^gatya/coinadd/$', views.coin_add, name='coin_add'),

    (r'^static_site/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': settings.MEDIA_ROOT}),
    )

sampleDjango/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sampleDjango.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^cms/', include('cms.urls', namespace='cms')), 
    (r'^static_site/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    
)

cms/models.py
from django.db import models


class Item(models.Model):
    '''アイテムのデータ'''
    name = models.CharField(u'名前', max_length=255)
    comment = models.TextField(u'コメント', blank=True)
    pic_name = models.CharField(u'画像名', max_length=255, blank=True)
    drop_num = models.IntegerField(u'出た回数', default=0)
    probability = models.IntegerField(u'確率(%)', default=0)

    def __str__(self):    # Python2: def __unicode__(self):
        return self.name


class User_data(models.Model):
    '''ユーザーデータ'''
    coins = models.IntegerField(u'コイン枚数', default=5)

    def __int__(self):    # Python2: def __unicode__(self):
        return self.coins

cms/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from django.db import transaction
from cms.models import *
import random


@transaction.commit_on_success
def drop_item(request):
    '''Itemの抽選'''
    rand = random.randint(0, 99)
    list = []
    all_item = Item.objects.all()

    '''ガチャの中身を入れる'''
    for item in all_item:
        i = item.probability
        while i > 0:
            list.append(item.id)
            i -= 1

    '''コインを投入'''
    coin_datas = User_data.objects.filter(id=1)
    for coin_data in coin_datas:
        if coin_data.coins > 0:
            coin_data.coins -= 1
            coin_data.save()

            '''ガチャる&出たアイテムのカウントアップ'''
            items = Item.objects.filter(id=list[rand])
            for item in items:
                item.drop_num += 1
                item.save()
            #渡すデータの設定
            data = dict(items=items)
        else:
            #渡すデータの設定
            data = dict()

    return render_to_response('cms/drop_item.html',
                               data,
                               context_instance=RequestContext(request))


def main_pic(request):
    '''初期ページ'''

    '''コイン枚数の呼び出し'''
    data_coins = User_data.objects.filter(id=1)
    for data_coin in data_coins:
        coin = data_coin.coins

    return render_to_response('cms/main_pic.html',  # 使用するテンプレート
                              dict(coinlist=range(0, coin), coinNum=coin),
                              context_instance=RequestContext(request))


def zukan(request):
    '''図鑑の表示'''
    sum = Item.objects.count()
    items = Item.objects.filter(drop_num__gt=0).order_by('id')

    return render_to_response('cms/zukan.html',  # 使用するテンプレート
                              dict({'items': items}, sum=sum),  # テンプレートに渡すデータ
                              context_instance=RequestContext(request))


@transaction.commit_on_success
def drop_reset(request):
    '''図鑑のリセット'''

    items = Item.objects.all()
    for item in items:
        item.drop_num = 0
        item.save()

    return redirect('cms:zukan')


def high_and_low(request):
    '''HighAndLowゲーム'''
    return render_to_response('cms/high_and_low.html',  # 使用するテンプレート
                              context_instance=RequestContext(request))


@transaction.commit_on_success
def coin_add(request):
    coin_datas = User_data.objects.filter(id=1)

    for coin_data in coin_datas:
        coin_data.coins += int(request.POST['add_coin_num']);

        if coin_data.coins > 5:
            coin_data.coins = 5

        coin_data.save()

    return redirect('cms:main_pic')

cms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<link href="{% static 'css/jquery-ui.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

cms/templates/cms/drop_item.html
{% extends "base.html" %}

{% block title %}メイン（テスト）{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 4px;
}
</style>
{% endblock %}

{% block content %}
	<head>
   		<script type="text/javascript" src="{{ MEDIA_URL }}/js/color.js"></script>
    </head>

  	<div class="page-header">
	    <table>
	    	<tr>
	    		<td width="400" rowspan="2">
	    			<h3>結果！</h3>
	    		</td>    	    		
	    		<td>
	    			<h5>メニュー</h5>
	    		</td>
	    	<tr>
    			<td height="45" width="120" align="center" >
    				<a href="{% url 'cms:main_pic' %}" class="btn btn-default btn-sm"><h5>メイン画面</h5></a>
    			</td>
    		</tr>
    	</table>
	</div>
	
    {% if items %}
    	{% for item in items %}
    		<h3>{{item.name}}</h3>
    	 		
    		<p><img src="{{ MEDIA_URL }}/images/{{item.pic_name}}" width="240" height="240" class="coverImage" id="pic"/></p>
    		  
    		<br /><br />
    	
    		<h4>{{item.comment}}</h4>
    	{% endfor %}
    {% else %}
    	<h4>コインがないよ！</h4>
    {% endif %}
    
    <a href="{% url 'cms:main_pic' %}" class="btn btn-default btn-sm">戻る</a>

{% endblock content %}

cms/templates/cms/high_and_low.html
{% extends "base.html" %}

{% block title %}ハイ&ロー{% endblock title %}

{% block extrahead %}
<style>
table 
  margin-top: 4px;
}
</style>
{% endblock %}

{% block content %}
	<head>
   		<script type="text/javascript" src="{{ MEDIA_URL }}/js/highAndLow.js"></script>
    </head>
	
  	<div class="page-header">
	    <table>
	    	<tr>
	    		<td width="400" rowspan="2">
	    			<h3>ハイ&ロー！</h3>
	    		</td>    	    		
	    		<td>
	    			<h5>メニュー</h5>
	    		</td>
	    	<tr>
    			<td height="45" width="120" align="center" >
    				<a href="{% url 'cms:main_pic' %}" class="btn btn-default btn-sm"><h5>メイン画面</h5></a>
    			</td>
    		</tr>
    	</table>
	</div>
	
	<h4>現在のカードより大きいか小さいか当ててね！<br/>
		３回連続正解で１コイン、５回連続で２コイン７回連続で４コインもらえます。<br />
		ただし、途中で負けたり、やめたりしたらコインはもらえません。</h4>
	<br/>
	<table width="580">
		<tr>
			<th>　　現在のカード</th>
			<th>　</th>
			<th>　　伏せカード</th>
		</tr>
		<tr>
			<td align="center">
				<img src="{{ MEDIA_URL }}/images/trump/z02.png"/width="190" height="280" id="card1">
			</td>
			<td align="center" width="80">
				<div id="title_label"><h2>HIGH</h2><br/><h3>AND</h3><br/><h2>LOW</h2></div>
				<h3 id="issue"> </h3>
			</td>
			<td align="center">
				<img src="{{ MEDIA_URL }}/images/trump/z02.png"/width="190" height="280" id="card2">
			</td>
		</tr>
		<tr height="100">
			<td align="center" colspan="3" height="130" >
				<input type="image" id="startB" src="{{ MEDIA_URL }}/images/start.png" width="130" height="100"/>
				<!--high・lowボタン-->
				<input type="image" id="highB" src="{{ MEDIA_URL }}/images/highB.png" width="195" height="100"/>
				<input type="image" id="lowB" src="{{ MEDIA_URL }}/images/lowB.png" width="195" height="100"/>
				<!--次へボタン・リトライボタン-->
				<input type="image" id="nextB" src="{{ MEDIA_URL }}/images/nextB.png" width="195" height="100"/>
				<input type="image" id="retryB" src="{{ MEDIA_URL }}/images/retryB.png" width="195" height="100"/>
				<!--csrf_token(javascript用)-->
				{% csrf_token %}
				<!--コインゲットボタン-->
				<input type="image" id="getB" src="{{ MEDIA_URL }}/images/get.png" width="195" height="100"/>
			</td>
		</tr>
	</table>
	
{% endblock content %}

cms/templates/cms/main_pic.html
{% extends "base.html" %}

{% block title %}メイン（テスト）{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 4px;
}
</style>
{% endblock %}

{% block content %} 
	<head>
		<script type="text/javascript">    		
			var $coinNum = {{coinNum}};
    		$(function() {
        		$("#gacha").click(function(){
        			if($coinNum>0){
            		 	$(this).replaceWith("<img src={{ MEDIA_URL }}/images/kapuseru.gif?d="+(+new Date)+"width='548' height='400' />");
            			
            			setTimeout(function(){
							location.href="{% url 'cms:drop_item'%}";
						},1800);
					}else{
						$("#coinImg").replaceWith("<h4>　　　　コインがないよ！</h4>");
					}
        		});
    		});
    	</script>
	</head>
	
	<div class="page-header">
	    <table>
	    	<tr>
	    		<td width="400" rowspan="2">
	    			<h3>ガチャるよ！</h3>
	    		</td>
	    		<td>    	    		
	    			<h5>メニュー</h5>
	    		</td>
	    		<td>
	    			<h5>ゲーム(コインをためる)</h5>
	    		</td>
	    	</tr>
	    	<tr>
    			<td height="45" width="120" align="center" >
    				<a href="{% url 'cms:zukan' %}" class="btn btn-default btn-sm" ><h5>　図鑑　</h5></a>
    			</td>
    			<td>
    				<a href="{% url 'cms:high_and_low' %}" class="btn btn-default btn-sm" ><h5>ハイ&ロー</h5></a>
    			</td>
    		</tr>
    	</table>
	</div>
    
    <table>
    	<tr>
    		<th>　コイン枚数（最大5枚）</th>
    	</tr>
    	<tr>
    		<td height="50">
    			<h4 id="coinImg"> </h4>
    			{% for i in coinlist %}
    				<img src="{{ MEDIA_URL }}/images/coin.png"/width="58" height="50">
    			{% endfor %}
    		</td>
    	</tr>
   	</table>
   	
   	<br/>
   	
    <input type="image" id="gacha" src="{{ MEDIA_URL }}/images/gachagacha.png" width="280" height="360"/>
    
{% endblock content %}

cms/templates/cms/zukan.html
{% extends "base.html" %}

{% block title %}図鑑{% endblock title %}

{% block extrahead %}
<style>
table {
  margin-top: 4px;
}
</style>
{% endblock %}

{% block content %}
	<head>
   		<script type="text/javascript" src="{{ MEDIA_URL }}/js/deleteDialog.js"></script>
    </head>
	<div class="page-header">
	    <table>
	    	<tr>
	    		<td width="400">
	    			<h3>モンスター一覧</h3>
	    		</td>    	    		
	    		<td>
	  				<table>
	    				<tr>
	    					<th>メニュー</th>
	    					<th>初期化</th>
	    				</tr>
	    				<tr>
    						<td height="45" width="120" align="center" >
    							<a href="{% url 'cms:main_pic' %}" class="btn btn-default btn-sm"><h5>メイン画面</h5></a>
    						</td>
    						<td>
    							<a class="btn btn-default btn-sm" id="deleteB"><h5>図鑑初期化</h5></a>
    						</td>
    					</tr>
    				</table>
    			</td>
    		</tr>
    	</table>
	</div>
    
    <h4>前{{sum}}種類</h4>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>画像</th>
          <th>アイテム名</th>
          <th>コメント</th>
          <th>回数</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td><img src="{{ MEDIA_URL }}/images/{{item.pic_name}}" width="80" height="80"/></td>
          <td>{{ item.name }}</td>
          <td>{{ item.comment }}</td>
          <td>{{ item.drop_num }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    
    <div id="dialog" title="図鑑内容の初期化">
		<p>図鑑を初期化しますか？</p>
		<!--ここがないとcsrfができない-->
		{% csrf_token %}
    </div>
{% endblock content %}